---
title: "BA810 individual assignment"
author: "Yuhong Lu (U68065591)"
date: "10/2/2019"
output: 
  pdf_document: default
---

# Setup
```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggthemes)
library(glmnet)
theme_set(theme_bw())
```

# Load housing dataset
```{r}
house <- read_csv('housing.csv')

# replace na value in total_bedrooms col
total_bedrooms_median <- median(house$total_bedrooms, na.rm = T)
house <- replace_na(house, replace = (list(total_bedrooms = total_bedrooms_median)))
```

# Split into training and testing
```{r}
set.seed(68065591)
train_index <- sample(nrow(house), 15000)

x_data <- model.matrix( ~ -1 + total_rooms + total_bedrooms + households + housing_median_age + population + median_income + ocean_proximity, 
                        house)
y_data <- house$median_house_value / 1e6

# training data
x_train <- x_data[train_index, ]
y_train <- y_data[train_index]

# testing data
x_test <- x_data[-train_index, ]
y_test <- y_data[-train_index]
```

# Run Lasso regressions
```{r}
est <- glmnet(x_train, y_train, alpha = 1, nlambda = 100)
est$lambda
length(est$lambda)
```

# Prediction
```{r}
y_train_hat <- predict(est, newx = x_train)
y_test_hat <- predict(est, newx = x_test)
dim(y_train_hat)
dim(y_test_hat)
```

# Compute MSEs
```{r}
mse_train <- vector()
for(i in 1 : ncol(y_train_hat)) {
  mse_train[i] <- mean((y_train_hat[,i] - y_train) ^ 2)
}

mse_test <- vector()
for(i in 1 : ncol(y_test_hat)) {
  mse_test[i] <- mean((y_test_hat[,i] - y_test) ^ 2)
}
```

# Aggregate all MSEs in a single dataset
```{r}
# Training MSEs
house_mse_train <- tibble(
  lamda = est$lambda,
  mse = mse_train,
  dataset = 'Train'
)
# Testing MSEs
house_mse_test <- tibble(
  lamda = est$lambda,
  mse = mse_test,
  dataset = 'Test'
)

house_mse <- rbind(house_mse_train, house_mse_test)
```

# Plot MSEs
```{r}
ggplot(house_mse, aes(lamda, mse, col = dataset)) +
  geom_line()
```

